variables:
  REGISTRY_URL: "https://mynexus.com/v1/"
  IMAGE_NAME: "keyauto"

stages:
  - lint
  - build
  - scan
  - deploy

pylint:
  stage: lint
  tags:
    - k8s-runner-amd64
  image: registry.gitlab.com/pipeline-components/pylint:latest
  script:
    - pylint **/*.py

# нужно создать переменную 'REGISTRY_AUTH' в которой прописать путь к конфигу .kube/config
docker-build:
  stage: build
  tags:
    - k8s-runner-amd64
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${REGISTRY_URL}\":{\"auth\":\"${REGISTRY_AUTH}\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_NAME}:${CI_COMMIT_TAG}"
  # запускать данный шаг только когда создаетс тег
  only:
    - tags
  # не запускать когда создается branch
  except:
    - branches

trivy-scan:
  stage: scan
  tags:
    - k8s-runner-amd64
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  script:
    - time trivy --download-db-only --no-progress --cache-dir .trivycache/
    - time trivy --cache-dir .trivycache/ image --exit-code 0 --no-progress --format template --template "@/contrib/gitlab.tpl"
        --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$IMAGE_NAME:$CI_COMMIT_TAG"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    reports:
      container_scanning: gl-container-scanning-report.json
  # запускать данный шаг только когда создаетс тег
  only:
    - tags
  # не запускать когда создается branch
  except:
    - branches

deploy:
  stage: deploy
  script:
    - sed -i "s/KEYAUTO_VERSION/${CI_COMMIT_TAG}/g" docker-compose.yml
    - docker stack deploy -c docker-compose.yml keyauto
  # запускать данный шаг только когда создаетс тег
  only:
    - tags
  # не запускать когда создается branch
  except:
    - branches
